### ISSUE TITLE
How to make hashes for ALL FILES?

### ISSUE THREAD

**Issue by ZarusMods** [BLAKE3-team/BLAKE3#105]
So in title how can i make hashes for all files via b3sum?

**Comment by oconnor663** [comment]
It's not clear to me what you mean. Could you ask your question again with lots of detail?

**Comment by ZarusMods** [comment]
I want to hash entire dir via b3sum not one by one files. My OS is Windows 10 x64 LTSC.

**Comment by oconnor663** [comment]
There's no one standard way to hash a directory of files. There are a lot of different things you need to think about to define the answer you want:

- Are filenames included in the hash? Presumably they have to be.
- How are filenames converted into bytes? This is especially tricky, because [different operating systems represent names differently](https://github.com/BLAKE3-team/BLAKE3/blob/master/b3sum/what_does_check_do.md), and you usually want the same directory (e.g. the same git repo checkout, or the same tarball) to hash the same across operating systems.
- Are file permissions included in the hash? File owners? This is also very OS-specific.
- Is everything concatenated into one stream to be hashed, or do you want to use a Merkle tree construction to represent the directory hierarchy?

These are not simple questions. You'll need to decide on your answers to these questions, and then write code yourself to implement your decisions. If you can get away with it, you might want to take a simpler approach like "just create a tarball of the directory, and then hash the tarball." (That works well if you want to keep the tarball around, but it might not work if you need to guarantee that different machines can reproduce the exact same tarball.) Or maybe "just check the directory into git, and then use the git commit hash or the git tree hash."
