### ISSUE TITLE
Add example how to hash file from Rust code

### ISSUE THREAD

**Issue by qarmin** [BLAKE3-team/BLAKE3#113]
Hi,
I need to hash entire file from Rust code, but I can't find how to do it exactly.
Should I read entire file o u8 array and then put it to hasher?

**Comment by oconnor663** [comment]
The relevant part of the readme is where the example code says "hash an input incrementally", but you're right that that's light on the details as far as how to do file IO in Rust. The simplest way is something like this:

```rust
let mut f = std::fs::File::open("foo.txt")?;
let mut hasher = blake3::Hasher::new();
std::io::copy(&mut f, &mut hasher)?;
println!("{}", hasher.finalize().to_hex());
```

The `std::io::copy` helper function is doing a read loop on the inside. If we wrote that out ourselves, it would look something like this (simplified a bit, omitting `ErrorKind::Interrupted` handling):

```rust
use std::io::prelude::*;

let mut f = std::fs::File::open("foo.txt")?;
let mut hasher = blake3::Hasher::new();
let mut buffer = [0u8; 16384];
loop {
    let n = f.read(&mut buffer)?;
    if n == 0 {
        break;
    }
    hasher.update(&buffer[..n]);
}
println!("{}", hasher.finalize().to_hex());
```

Those approaches are better than reading the entire file into memory all at once, because allocating a ton of memory is bad for performance, and also because we usually want to be able to handle files that are too large to fit in memory.

If you stare at the code of `b3sum`, you'll find that it tries to use a more interesting strategy called memory mapping. That's a performance optimization that doesn't _really_ matter until you start hashing very large files using multithreading. One upside of memory mapping is that the interface is extremely simple when it works. (It's like reading the entire file into a `Vec<u8>`.) But one downside is that there are a lot of cases where it doesn't work, so you always need to include fallback code using a read loop, so the final code isn't actually simpler. Anyway, this is probably more than you wanted to know :)

**Comment by oconnor663** [comment]
I'll go ahead and close this one, but feel free to comment with more questions.

**Comment by qarmin** [comment]
That should be enough.
Thanks a lot for your help.
