### ISSUE TITLE
How to make b3sum write a text?

### ISSUE THREAD

**Issue by ZarusMods** [BLAKE3-team/BLAKE3#124]
How to make b3sum write a text?
So i making hashes, and they are saved in hash.blake3
I want to add a warning that if some optional files are missing it is ok.
How can i do that?

**Comment by oconnor663** [comment]
It sounds like you're using `b3sum --check`, and your asking how to change the behavior of that command? Let me know if I've misunderstood you. Right now there's basically no way to change it. But maybe I could suggest some ways to write a wrapping script that might do what you want? For example, do you actually need to change the error code returned by the program? Or do you just need to print a message if it fails?

**Comment by ZarusMods** [comment]
Here is example. User have a game, but problem is user forgot to install language pack. How can i trigger b3sum to say a text "WARNING! YOU DON'T HAVE ANY LANGUAGES INSTALLED!"

**Comment by oconnor663** [comment]
There's no way to make `b3sum` print that for you. You'll need to print it yourself, from whatever code is calling `b3sum`. It sounds like using `b3sum --check` might not be a great fit for the problem you're trying to solve. If you have a list of files and their expected hashes, it might make more sense to just run `b3sum` on each file individually, and then you can print an error that's more meaningful to your users based on what's missing.

The design of `b3sum --check` (just like `md5sum --check` and all other commands like it) is geared towards situations where the files are almost always expected to be correct. Maybe the only way they could be wrong is if a network error happened, or a disk error happened, or there's some attacker trying to mess with you. In those cases, an error will be difficult to understand and debug, but we might consider that ok because either 1) it's expected to almost never happen, or 2) your code has no idea what the cause of the error would be anyway, so it can't really do any better.

However, in your case, it sounds like you're dealing with some common errors that might have predictable causes, and you want to be able to give your users some helpful advice. Custom code is going to be much better than `b3sum --check` for that use case.
