### ISSUE TITLE
what's the difference between the "c" and the non-c tags? (eg "c-0.3.7" vs "0.3.7") ?

### ISSUE THREAD

**Issue by divinity76** [BLAKE3-team/BLAKE3#125]

**Comment by oconnor663** [comment]
I've been adding "c-" tags whever the C implementation gets an important bugfix. Since we're not using any sort of package manager for C, I was worried that people who vendor our code might not have any indication of when it's important to re-vendor. This set of tags was the first thing I thought of, though it's not very clear either. Let me know if you have any other ideas.

**Comment by divinity76** [comment]
thanks for explaining; and no, i don't have any better idea ^^
