### ISSUE TITLE
Expose get_cpu_features?

### ISSUE THREAD

**Issue by erijo** [BLAKE3-team/BLAKE3#129]
As I [commented here](https://github.com/ccache/ccache/issues/689#issuecomment-713349046), there could be value for other projects to be able to use BLAKE3's run-time detection of CPU features. Would you be willing to accept a PR that exposes `get_cpu_features()` in some way? Either directly as `blake3_get_cpu_features()` (including the enum) or perhaps as separate getters: `blake3_cpu_supports_avx2()`, etc.?

**Comment by sneves** [comment]
Well, our CPU feature detection is a bit overly specific to our specific assembly kernels, so I'm not sure it'd be the best choice for 3rd party projects. There are a zillion CPU features we are not detecting, and that's just on x86.

Have you looked at, say, https://github.com/google/cpu_features? Since ccache itself is using CMake, integration shouldn't be too horrible.

**Comment by erijo** [comment]
I understand if you don't want to expose the CPU detection for 3rd party projects. For ccache it would have been a perfect fit as BLAKE3 is already integrated and the only flag that's needed is the AVX2 one. But ccache can probably easily patch BLAKE3 to expose a small function for the need that ccache has.

Closing this issue. Thanks for your input!
