### ISSUE TITLE
Provable data possession

### ISSUE THREAD

**Issue by saracen** [BLAKE3-team/BLAKE3#146]
I'm currently writing a system that intends to use content-defined chunking to break up large data files into smaller chunks for the purposes of deduplication.

A client will break up a directory of data into 2kb - 64kb chunks and only transfer them to the server if the server doesn't already hold a copy.

Each chunk is content-addressable, with the "filename" of each chunk being the hash of its contents (160-bits, blake3).

The storage server is shared by multiple clients and I'm treating the 160-bit address of each chunk as public information. Although typically, if a client generated the 160-bit hash, this would be enough to prove the client was in possession of the data, I'm expecting that such hashes could be leaked (via logging etc).

I want a way for the client to prove to the server that it does in fact possess the data, without the client having to fully upload the data. Proof is a requirement, so that the server can tag the chunk, so that later the client is able to access the data. Otherwise, an evil client could lay claim to a data chunk that it just happens to know the hash of.

I'm writing up this issue because in https://github.com/BLAKE3-team/BLAKE3/pull/85, you asked for use-cases of potentially requiring a serialized Hasher.

I'm not entirely sure I would require a serialized Hasher for this, but I took this as an indicator that such an issue would be welcome here for discussion.

Right now, I feel like my options are:

1. If a client claims it owns some data, the server asks the client to prove it by appending some random data to the existing hash. The server does the same (by unserializing stored state) and the hashes are compared. Unfortunately, the state is quite large, but certainly better than obtaining a block from object storage and rehashing the entire thing. For hashes susceptible to length extension attacks, this solution would not work, but I believe I'm safe to do this here.
1. Produce a larger hash, say 416-bits. 160-bits would be the address and public, the remaining 256-bits would be treated as private, and the server would challenge the client to provide 64-bits of it at an arbitrary offset.
1. Do something similar to 2, but store the state of the digest, so that the arbitrary offset could be much larger. But this likely has the same drawback as 1, in that the state is probably quite large to store.
1. Another idea that I'm not considering :smile:

Thank you.

**Comment by oconnor663** [comment]
I'm not sure I totally get what's going on in your use case. (The server is storing some data, but the client is also storing it? Why both? I think I'm missing something.) But in general if you want me to prove that I'm storing some string that you're also storing, the simplest way might be to ask me for the `keyed_hash` of that string under a random 256-bit key of your choice.** Because of the way keying is done in BLAKE3, that forces me to store the original string in its entirety, and there's no shortcut like "hash the string once and save the incremental state" that I can use to avoid storing it. (This is also true of HMAC.)

Notably, this property does _not_ apply if you ask me to append extra bytes to the file (because that's equivalent to regular old incremental hashing), or if you ask me to seek to a new section of the extended hash output (ditto). In both of those cases, I can compute the incremental state once and save that state instead of its input. It seems like you recognize this fact in your description of option number 1 above. But it's not clear to me whether you recognize that if the server can avoid a full re-hash in this way, then the client can too, and the protocol is no longer proving that the client is storing the input.

A totally different approach, which you might've already considered, is to challenge me to send you random samples of the file I'm storing at offsets you choose. There might be some thorny questions here about whether I can cheat this process with lossy compression (and in general I think this is an active research area, so apologies if I have this part wrong). But if we focus on the simpler case of storing a large file full of random-looking, uncompressible bytes, then honestly storing the file should be the only way I can reliably answer your challenges. The upside of this approach is that neither of us has to do very much work in the challenge process, compared to the first approach that requires both of us to read and re-hash a potentially enormous file.

The [Bao project](https://github.com/oconnor663/bao), which is based on BLAKE3, is potentially useful in this sort of challenge protocol. If you know the BLAKE3 hash of the file I'm storing, you can request arbitrary "slices" of the file, which Bao can then verify against the hash you know. This only requires you to know the hash, and doesn't require you to store any of the file itself. If you want to play with it, the `bao slice` and `bao decode-slice` commands work today. That said, you mentioned that you're doing content-defined chunking, and BLAKE3/Bao do fixed chunking, so I don't know if this sort of thing will actually help with your use case.

** As an aside, it can be a little sketchy to MAC something using a key of someone else's choosing, because you might worry about weird scenarios where some bad guy impersonates the server and exploits this protocol to learn the MACs of files they don't actually possess. To be more robust to this sort of thing, you could have both parties contribute random keys, and hash them together to produce the MAC key. Alternatively, you could either pre-process the key or post-process the MAC using `derive_key` with a unique context string like `"@saracen's provable data possession protocol token"`, to effectively guarantee that the token will never have any interaction with any other protocol.

**Comment by blinkdog** [comment]
>I want a way for the client to prove to the server that it does in fact possess the data, without the client having to fully upload the data. Proof is a requirement, so that the server can tag the chunk, so that later the client is able to access the data. Otherwise, an evil client could lay claim to a data chunk that it just happens to know the hash of.

Have the server randomly generate a set of ranges between 0 and the block size, so you have an ordered list of tuples:

(2622, 51331)
(11217, 18348)
(28291, 52241)
...
(28874, 33974)

now throw in one with a fixed point at 0, and another at the block size:

(0, 13734)
(18313, 65535)

This is probably sufficient, but if you wanted to be absolutely sure the client has absolutely every byte in the block, you could sort and walk the ranges list to make sure the ranges overlap and cover every byte. Fill in any missing gaps as you walk.

Now, shuffle the tuple list, then send it to the client.
The client should compute the hash of all the bytes in the covered ranges, in the order sent.
Not one hash per range, but bytes of range 0, append bytes of range 1, append bytes of range 2, etc. to compute one final hash.
As the server, you have the data and generated the ranges; you can easily compute that hash.
If the client can provide a hash that matches, you know they've got all the data.

Protocol:
- Client connects to server
- Client says: I want to prove for $BLOCK_HASH
- Server provides range tuple challenge
- Client provides challenge hash
- Server checks hash to decide if client is allowed to access $BLOCK_HASH in the future

**Comment by saracen** [comment]
@oconnor663 

> (The server is storing some data, but the client is also storing it? Why both? I think I'm missing something.)

> In both of those cases, I can compute the incremental state once and save that state instead of its input. It seems like you recognize this fact in your description of option number 1 above. But it's not clear to me whether you recognize that if the server can avoid a full re-hash in this way, then the client can too, and the protocol is no longer proving that the client is storing the input.

Apologies, I definitely wasn't clear enough. I think using the term "provable data possession" is also misleading, as those protocols are usually a client trying to determine that a server says it's storing the data it says it's storing.

---

My system consists of clients (for uploading/downloading), a server (that performs authentication and stores metadata) and object storage (s3). The clients only talk to my server, and only my server talks to s3.

- `client_saracen` authenticates and tells the server it has the hash:content `abcd:hello world` for upload.
- The server doesn't have this data. So it lets `client_saracen` know the transfer can begin.
- The client sends the object, the server pushes this object to S3 and keeps its own record `client_saracen` owns `abcd`.

Later:

- `client_saracen` authenticates and tells the server it wants `abcd` for download.
- The server verifies ownership and sends the data.

Later:

- `client_oconnor663` wants to also upload `abcd`
- The server has this object already, so doesn't need the object to be transferred. However, it cannot create a record stating that `client_oconnor663` owns `abcd`, otherwise `client_oconnor663` can download the data without first proving it ever had it.

--- 

I only need to prove that the client has the data at the time of upload. Ideally, the server only needs access to metadata about the object, and not the full object, to verify the clients proof, which is why it storing some kind of resumable hash would be okay here.

@blinkdog

That might work.

I guess this would mean that the first time the server sees the object, I would need to produce multiple hashes of different ranges and store those on the server as part of object's metadata.

I do wonder whether the nature of content-defined chunking would leak data though. If we shuffle the ranges, is there a chance the ranges only cover some guessable data?

Is it a better solution than the server just generating a much larger hash, and then asking the client to prove whether it also knows ranges from that?

**Comment by oconnor663** [comment]
Ah got it. In that case, maybe the simplest thing is for the public ID of each file to be its double hash, `H(H(file))`. When clients want to upload a file, they provide the regular hash, `H(file)`. Both parties then compute `H(H(file))`, the server so that it can see whether the file already exists, and the client so that they can store the ID for later retrieval. Double hashing means the server doesn't need to store `H(file)` or reveal it to the object store. Maybe that's good enough?

But it sounds like you're also worried about situations where `H(file)` happens to leak for unrelated reasons. Maybe some applications just like to publish the hashes of files from time to time, without realizing that the server doesn't expect them to do that? To deal with this situation, we could pick some `H` that applications are unlikely to use for other purposes and therefore unlikely to randomly leak the output of. This is what `blake3::derive_key` is tailor-made for. You give it a unique context string, and then you're guaranteed that it's output is domain separated from anything else that doesn't use that exact same context. (The second `H` could be `blake3::derive_key` again, or it could be just `blake3::hash`. Doesn't matter I think.)

One possible downside of this approach is that `blake3::hash(file)` and `blake3::derive_key("context...", file)` can't share any work. They both need to digest the entire file. Since we're already imagining that clients like to compute the regular hash for their own purposes, maybe it would be better if they had the option to avoid repeating that work? It seems like this is what you were getting at with the original options you proposed at the top. Either of those could work, either appending some extra data to the file, or taking some output bytes other than the first 32. (Though I think a fixed public suffix or a fixed output offset would work. I don't see why either would need to be variable.)

That said, I'm not really a fan of these strategies, for a couple reasons:

1. They don't seem like they're robustly solving the problems they set out to solve. Applications that might leak 32 bytes of hash output might also leak 1000 bytes. Two files might differ from each other in exactly the suffix you planned on appending.
2. Do many applications care about hashing a file two different ways? That duplicated work is just CPU work, while the application is more likely to care about disk IO or network IO, neither of which needs to be duplicated.

So I lean towards either a dead simple approach with just the vanilla double hash, or a more rigorous approach with `derive_key`, rather than trying to get fancy with something in between.

As another random aside, it seems like the intended design properties of this system might still have some privacy issues. I'm effectively able to ask the server whether anyone has uploaded a given file before. That could have problematic interactions with things like watermarked files.

**Comment by saracen** [comment]
> But it sounds like you're also worried about situations where H(file) happens to leak for unrelated reasons. Maybe some applications just like to publish the hashes of files from time to time, without realizing that the server doesn't expect them to do that?

Yeah, it's exactly that.

Git LFS is actually a pretty similar system. Rather than store large files in a Git Repository, git can just be asked to store the sha256 of a file, and the file's content is instead uploaded to an LFS server. The hashes sit within a git repository, so they're certainly not considered a secret. That git repository can go from public to private, or vice versa, and it's the LFS server and authentication that determines who is allowed to download the file.

You could also imagine that a CI job for a private repository, that has public logs, might emit a "Uploading <sha256> to LFS server..." message. If such a system treated additional hash output as secret, it's unlikely to leak in the same way.

> maybe it would be better if they had the option to avoid repeating that work? It seems like this is what you were getting at with the original options you proposed at the top

This was the hope, but given the chunks are relatively small, and would only need to be done when the server asks for proof of possession, you're right that this wouldn't be a concern.

> As another random aside, it seems like the intended design properties of this system might still have some privacy issues.

This is true, and something I need to certainly give additional thought.

When a Git LFS server sees a file for the first time at a project boundary, it requires the full file to be uploaded. So the proof of possession is supplying the entire file... but the server then likely discards the data if already known.

I guess it's likely that the same privacy issue is true here, but might only be revealed through a timing attack.

---

The `derive_key` method makes a lot of sense.

I know that much of this design could apply to any hash and might not be all entirely relevant to blake3 so I really appreciate the time you've taken here to help. Thank you!
