### ISSUE TITLE
Hash many with different input sizes

### ISSUE THREAD

**Issue by fernmig** [BLAKE3-team/BLAKE3#177]
Does the AVX2 hash many handle different input sizes? I don't see a parameter to blake3_hash8_avx2 for this.

**Comment by oconnor663** [comment]
The relevant parameter here `blocks`. So that function supports hashing inputs of any integer multiple of the block size (64 bytes). Typically the two values that'll get used here are 1 (for hashing 64-byte parent nodes) and 16 (for hashing 1 KiB chunks of input). So as it stands, that function is more flexible than it really needs to be, and some of this might get refactored in the future. The reason it wound up the way it is, is that I found that having a dedicated function for the 1 KiB case ended up unrolling the loop and then taking forever to compile a ridiculously bloated binary. It's likely that a more experienced C programmer could do a better job of this than I was able to do.

**Comment by fernmig** [comment]
I see. What if we need to hash inputs less than block size something like 20 or 32 bytes?

**Comment by oconnor663** [comment]
If you have a short input, or just an input that isn't an exact multiple of the block size, the final (possibly only) block is padded with zeroes to be 64 bytes. You can find the formal description of this in section 2.4 of [the BLAKE3 paper](https://github.com/BLAKE3-team/BLAKE3-specs/blob/master/blake3.pdf). If you're interested in getting a concrete understanding of that BLAKE3 is doing on the inside, [the reference implementation](https://github.com/BLAKE3-team/BLAKE3/blob/master/reference_impl/reference_impl.rs) is also a good place to start. That implementation doesn't have any of the fancy SIMD optimizations that you'll see in the production implementations, but when it comes to short or uneven inputs, those implementations will fall back to the same approach that the reference implementation is using.
