### ISSUE TITLE
BLAKE3 collision resistance

### ISSUE THREAD

**Issue by abitrolly** [BLAKE3-team/BLAKE3#194]
How collision resistant are BLAKE3 hashes of different length comparing to the following table from [Wikipedia](https://en.wikipedia.org/wiki/Hash_function_security_summary#Collision_resistance)?

Hash function | Security claim | Best attack | Publish date | Comment
-- | -- | -- | -- | --
SHA256 | 2**128 | 31 of 64 rounds (2**65.5) | 2013-05-28 | Two-block collision.[3]
SHA512 | 2**256 | 24 of 80 rounds (2**32.5) | 2008-11-25 | Paper.[4]
SHA-3 | Up to 2**512 | 6 of 24 rounds (2**50) | 2017 | Paper.[5]
BLAKE2s | 2**128 | 2.5 of 10 rounds (2**112) | 2009-05-26 | Paper.[6]
BLAKE2b | 2**256 | 2.5 of 12 rounds (2**224) | 2009-05-26 | Paper.[6]

I am especially interested to compare BLAKE3 128 to BLAKE2s 128 as it is the digest size (#107) I'd like to use.

**Comment by sneves** [comment]
The collision resistance security claim of BLAKE3 is the same as that of BLAKE2s, i.e., `2**128`.

**Comment by abitrolly** [comment]
@sneves and if I want to used 128bit hashes.. Does BLAKE3 allows to produce them? What will be their security claim (`2**64`?) and can they be considered secure for content addressing?

**Comment by sneves** [comment]
Yes, the collision resistant is `min(2**(output_size/2), 2^128)` for arbitrary output sizes.

**Comment by oconnor663** [comment]
> Does BLAKE3 allows to produce them?

Yes, for example the Rust API provides [`OutputReader::fill`](https://docs.rs/blake3/1.0.0/blake3/struct.OutputReader.html#method.fill), which will produce an output of any size you like. Shorter outputs are prefixes of longer ones, so if you want an output shorter than 256 bits, another way to get the same result is to just truncate the standard output. There's no performance difference between either approach.

**Comment by abitrolly** [comment]
One last question to explain the collision resistance. Both BLAKE3-128 and BLAKE2s-128 have a collision resistance of `2**64`.

Does that mean that the minimal file size where collisions are possible is 18.4467441 EB (2**64 in [exabytes](https://en.wikipedia.org/wiki/Orders_of_magnitude_(data)))?

**Comment by abitrolly** [comment]
In case you're curious - I am trying to add BLAKE into W3C SRI standard - https://gitcoin.co/grants/3451/add-blake2-into-w3c-sri-spec

**Comment by elichai** [comment]
@abitrolly No, it's probability, so for any 2 randomly given inputs A and B where A != B, there's a 1/2^64 chance that `H(A)==H(B)`.
So the more inputs you sample the larger the probability that some pair of unequal inputs will have the same hash.

Theoretically it is as probable that 2 single bytes inputs have the same hash as 2 huge files having the same hash.

**Comment by abitrolly** [comment]
@elichai and what if I want construct input B (which is != A) with a specific goal of creating a collision? Is it possible to convert probability into the minimal size of data that needed to be generated to generate a collisions?

Can we take a file as a coin, throw as a comparision to another unique file, and flip as a collision between these files to explain the probability? Then we need to throw it 2^64 times to ensure we've a got flip, right? Each file with unique content is a throw. So there are 256  (2^8) unique files with a size of 1, then 2^16 (65536) unique files with the size of 2, 4 bytes give 2^32 combinations, and bruteforcing 8 bytes file generates 2^64 throws that are necessary to generate a flip. I feel like there is some substantial flaw in my thinking, but I don't know where.

**Comment by elichai** [comment]
@abitrolly If you mean by "minimal size of data that needed to be generated to generate a collisions"  to be guaranteed collision, then you need to match the output size + 1 (here that will be 2^128+1) - This is from the [pigeonhole principle](https://en.wikipedia.org/wiki/Pigeonhole_principle).

Now when people speak about the collision resistance of something, they take into account the [Birthday Bound](https://en.wikipedia.org/wiki/Birthday_attack), Which roughly means, that if you have some function `f(x)` that randomly maps x to an output space of 2^n, then by sampling 2^(n/2) there's ~50% probability that 2 inputs you've sampled will produce the same output.

As for your examples, if your application doesn't allow inputs with more than X bits, then you've restricted the input space of the hash function, but you've also made it much easier to break preimage resistance as the attacker can just brute forcefully exhaust the input space. 
Especially as you've shown that even if you allow 8 bytes input then that is enough to get 2^64 inputs which have 50% probability of containing a collision in the output (note that this assumes that if your input is incremental the output is still uniformly distributed)

If you want to learn more about the birthday bound Dan Boneh has a great video about the mathematics of it: https://www.youtube.com/watch?v=5VY2KEh9WrE.

**Comment by oconnor663** [comment]
> Does that mean that the minimal file size where collisions are possible is 18.4467441 EB (2**64 in exabytes)?

"Minimal file size" isn't usually how we think about these things, but it would be much more accurate to say that the minimal file size is **64 bits**. Much smaller than you were thinking.

Saying that you have 64 bits of collision resistance implies that you'd need to try 2<sup>64</sup> inputs to have a ~50% chance of finding a collision. One way to generate that many inputs is to try all the integers from 0 to 2<sup>64</sup>. Those all fit in 64 bits, which is why you don't need any large files like you were imagining. In short, exponential growth is very fast.

**Comment by abitrolly** [comment]
Thanks for the explanation. That's not what I expected, indeed.

> Having 64 bits of collision resistance means that you need to try 264 inputs to have a ~50% chance of finding a collision.

So given the average hashrate of BLAKE3 as 6.866 GiB/s (2^30 bits) the time to find a BLAKE3 collision would be (2^64/(6.866*2^30))/3600/8760=79.34 years. Or 80 `c5.metal` instances running for a year.

![image](https://user-images.githubusercontent.com/8781107/133648222-1856eae1-69ee-4084-be87-015ff74c4b6c.png)

And it will take only 2^64/((10^12)*122*10^6)=0.1512 seconds to find a collision using Bitcoin network, which a hash rate of about 122M TH/s (https://ycharts.com/indicators/bitcoin_network_hash_rate).

And the total number of bits passed though the hasher to get a ~50% of collision will still be 2^64 or 18.4467441 EB.

**Comment by oconnor663** [comment]
> (2^64/(6.866*2^30))/3600/8760

There are some subtleties here, because the block size of BLAKE3 (and BLAKE2s) is 64 bytes, and you have to be hashing full blocks to get the full value of that GB/s figure. In our case we're only hashing 64 bits = 8 bytes out of 64, so real throughput will be lower by at least a factor of 8. (In a sense, 7/8ths of our work gets wasted hashing padding.) This also assumes that you get to take full advantage of our parallelism optimizations, and _in theory_ that's equally possible for "many small inputs" as it is for "one big input". But in practice our implementations don't provide any way to access those optimizations in the "many small inputs case", so you'd have to write a lot of custom code to make this work. (Notably, my BLAKE2 implementations [do provide these APIs](https://docs.rs/blake2s_simd/0.5.11/blake2s_simd/many/index.html), but probably no one actually uses them.)

On the other hand, each of those c5.metal instances has ~46 physical cores, so there's a big speedup that you should include in the math :)

> And the total number of bits passed though the hasher to get a ~50% of collision will still be 2^64 or 18.4467441 EB.

I think since each int is 64 bits, it's more like 2<sup>64</sup> * 64 = 2<sup>70</sup>. But then again, because these aren't full blocks, the majority of compression function input is actually block padding null bytes, and it's not clear whether we should count those as "real input" or not.

But yes long story short, 64 bits of security is not a lot, and you can brute force it with a budget that's big by individual standards but small by tech company or government standards. And those numbers will keep going down over time.

**Comment by abitrolly** [comment]
> But yes long story short, 64 bits of security is not a lot, and you can brute force it with a budget that's big by individual standards but small by tech company or government standards. And those numbers will keep going down over time.

That answers my question if a hash with 2^64 collision resistance is enough for content addressing, and the answer is unfortunately - no. Because it would be too easy for a government or a tech company to produce a collision, so some additional checks are needed.. I hoped 128-bit hashes could be used, because they double save the space for indexes.

An example of the real world collision would still be welcome. Maybe it is still possible to create a content addressing network design that protects against collision attacks or warns about them without relying solely on a single hash size.

**Comment by abitrolly** [comment]
Thanks for the answers. Maybe not for content addressing, but I would still consider using 128-bit hashes as a checksum in applications that are not that critical that some government would be interested in breaking them.
