### ISSUE TITLE
Blake3 Extensions

### ISSUE THREAD

**Issue by bastiencaillot** [BLAKE3-team/BLAKE3#197]
Hello @Blake3-team and @oconnor663, I'm 17 years old and I'm passionate about cryptography and I had a question: why did you "complicate" your life with the extensions in Blake3's C source code? Indeed, most compilers automatically define the extensions that can be used (SSE + AVX + ADVANCED SIMD/NEON). For example, people using Clang or GCC will not need to add !defined(BLAKE3_NO_SSE2) in a production Makefile because this extension will already have been implemented by the compiler. This will not change the time spent by people using a compiler that does not support the above extensions because they already have to do it for the current version of Blake3, for example by specifying that !BLAKE3_NO_SSE41 corresponds to the SSE4_1 extension, but people using for example Gnu Compiler Collection will have the file automatically built.

          #if !defined(BLAKE3_NO_SSE41)   would therefore be modified by #if defined(__SSE4_1__)
 
          #if !defined(BLAKE3_NO_AVX2)   would therefore be modified by #if defined(__AVX2__)

          #if !defined(BLAKE3_NO_SSE2)   would therefore be modified by #if defined(__SSE2__)
         
          #if !defined(BLAKE3_NO_AVX512)   would therefore be modified by #if defined(__AVX512F__) && defined(__AVX512VL__)

          #if defined(BLAKE3_USE_NEON) would therefore be modified by #ifdef __ARM_NEON

Indeed, as explained in your c/README.md, the AVX512 extension requires both AVX512F and AVX512VL .

Congratulations again for all your work and have a nice day ;)

External links: 

https://gcc.gnu.org/legacy-ml/gcc-patches/2015-01/msg02717.html

https://stackoverflow.com/questions/28939652/how-to-detect-sse-sse2-avx-avx2-avx-512-avx-128-fma-kcvi-availability-at-compile

https://developer.arm.com/documentation/101028/0009/C-language-extensions

**Comment by oconnor663** [comment]
The reason we don't rely on compiler-defined flags is that we don't want to silently build an incomplete library. The default build should produce implementations for SSE2/SSE4/AVX2/AVX512, so that the runtime performance of the library doesn't depend (much) on what machine you built it on. Otherwise a lot of people would end up shipping or benchmarking these incomplete builds and getting poor performance, and it would be almost impossible to figure out why.

But now that you mention it, we did make a different choice in the Rust library. There, the `build.rs` file explicitly checks for AVX-512 support in the C compiler, and it skips building AVX-512 if that support is missing. There are a couple reasons for this difference:

- It's less likely that someone building a Rust crate is using an ancient C compiler, so the number of people who run into mysteriously-poorly-performing build artifacts should be smaller.
- On the other hand, some Rust users don't have a C compiler at all, especially in cross-compilation scenarios.

Now that you mention it though, a C project shipping BLAKE3 as a dependency might want to make similar tradeoffs, if the developers understand the performance downsides involved and would rather prioritize build compatibility with old compilers. I wouldn't want that to be the default, again because I'm worried about unexpected failures passing silently. But if we added a new explicit flag like `BLAKE3_AVX512_IS_OPTIONAL`, which allowed AVX-512 code to be automatically skipped when compiler support was missing, would that be helpful for your use case?

**Comment by sneves** [comment]
`__AVX2__` and such are enabled when the compiler is targeting architectures with AVX2 etc. `blake3_dispatch.c` is meant to be compiled without such special targeting, otherwise it would be pointless.

Furthermore, `__AVX2__` and the others do not exist everywhere where their respective intrinsics are supported. So either way you'd need to have some other way to signal this, unless your goal is to stay dependent on the GCC(-compatible) toolchain.

**Comment by bastiencaillot** [comment]
Thanks to @oconnor663 and @sneves for your help. I had forked Blake3, so I will be able to make changes in my repository. I close this issue. Good continuation 😊
