### ISSUE TITLE
Possible methods to detect NEON

### ISSUE THREAD

**Issue by odiferousmint** [BLAKE3-team/BLAKE3#211]
Hey. I noticed here https://github.com/BLAKE3-team/BLAKE3/blob/5957d7d48f0626bfa9cd21339b0db61c72391ebe/c/blake3_dispatch.c#L130 that you may want to detect NEON.

What about something like https://github.com/jedisct1/libsodium/blob/6cd2677d44a715103304dbe58f1761f966acc079/src/libsodium/sodium/runtime.c#L67?

**Comment by oconnor663** [comment]
Preprocessor flags like `__ARM_NEON` are compile-time features. They can tell us things like "the compiler knows how to compile NEON" or "all CPUs of the target architecture definitely support NEON". But there are are some architectures (particularly ARMv7) where we can't necessarily know in advance whether the runtime CPU will have NEON support, because CPUs with and without support both exist within that architecture. We'd need a way to ask the machine at runtime, "Do you actually support NEON?" And that's the thing that does't exist. There's no standard ARM instruction that lets us ask this. (In contrast to x86, where there is such an instruction.) There are [other ways to get this information](https://stackoverflow.com/questions/26701262/how-to-check-the-existence-of-neon-on-arm), but they're OS-specific.

In practice this is becoming less important, because most new consumer and server ARM chips are AArch64, which is in the "all CPUs of the target architecture definitely support NEON" category. Last month's 1.1.0 release of BLAKE3 enabled NEON optimizations by default for AArch64.
