### ISSUE TITLE
Blake3 - pls help me maximaze performance.

### ISSUE THREAD

**Issue by Alg0ritmus** [BLAKE3-team/BLAKE3#216]
Hi,
I am kindly asking for help. I just wanted to speed up hashing process, but unfortunately I still don't know where could be the problem.
I've tried to use parallel approach (using rayon) as I found in docs, which definitely helped but it's still pretty slow comparing to [Python implementation](https://github.com/oconnor663/blake3-py). I'm wondering If there is better way to hash file content or I'm missing something. My goal is to fully take advantage of SIMD and paralelizm.

[Here](https://github.com/Alg0ritmus/Blake3-testing/blob/master/rustTest/src/main.rs) is my code.

I know that this is probably inappropriate way of asking for help, but I'd really appreciate any kind of help. Thanks in advance.

**Comment by oconnor663** [comment]
> pretty slow comparing to Python implementation

I'm happy to help, but it's import to start with complete repro steps, so that I know I'm seeing the same thing you're seeing. Could you tell me exactly what commands I should run, and also tell me what output and timing you're getting from each?

**Comment by Alg0ritmus** [comment]
First of all thank you for your time. 
I added myB3.py (code where I'm testing python implementation).

I wasn't able to upload 200MB on git, so [here](https://drive.google.com/file/d/16NKRLXFHK546v5ybxFIXM57TrMPYuDMs/view?usp=sharing) is external link for testing file.
(Changing Path directory in both codes may by needed)

After changing path dir. in code just type :
py myB3.py  -> for python code
cargo run -> for Rust (in rustTest directory)

_OUTPUTS:_

Python: (I used multithreading option set to True)
004fa4cbf244e9d14d76b409e7481e6095b976cb6e63bfa3d533ba1df465261c
**time**: 0.156s 


________________________________________________


RUST: (I used update_rayon method for paralelizm)
ee90c63b8027dbbfc98059fc91fa91b23224d33b70b1c6203d2050c0256d0a74
**time**: 3.61s

[My repository](https://github.com/Alg0ritmus/Blake3-testing/tree/master)

* Output is different probably because I used different encoding( byte literal for PY, bytes for RUST impl.)

**Comment by oconnor663** [comment]
Perfect! Thank you.

One thing I'm noticing is that you're using `cargo run` for benchmarking. That's a problem because it defaults to debug mode and turns off compiler optimizations. You want `cargo run --release` anytime you're measuring performance. (Or something like `cargo bench`, which defaults to release mode.) I'm not sure this explains the massive difference you're seeing, but it might be a factor.

Also I think the reason you're getting different output in Python is that by default, Python reads files in "universal newlines" mode. Your file contains Windows-style \r\n newlines, and Python coverts those to Unix-style \n. If you read the file directly in binary mode ("rb" instead of "r"), you'll get the same answer Rust did.

Anyway yes, here are some numbers I'm seeing. I've run each one five times and reported the best of five:

- `python myB3.py`
```
0.004027589995530434
004fa4cbf244e9d14d76b409e7481e6095b976cb6e63bfa3d533ba1df465261c
```

- `cargo run`
```
result from update ee90c63b8027dbbfc98059fc91fa91b23224d33b70b1c6203d2050c0256d0a74
Elapsed: 8.61ms
```

- `cargo run --release`
```
result from update ee90c63b8027dbbfc98059fc91fa91b23224d33b70b1c6203d2050c0256d0a74
Elapsed: 4.06ms
```

So overall, the timing I'm seeing from your Python code on my machine is consistent from what I'm seeing from your Rust code under `--release`. But even without `--release`, it's only about a factor of two slower. (That's becasue most of the heavy lifting in the `blake3` crate is being done in assembly code, which doesn't depend on optimization settings.)

So that leaves us with a bit of a mystery. Why are things so much faster on my machine than yours? The Rust code is definitely extra slow for some reason, but even the Python code seems ~40x slower than what I'm seeing. Could you say more about what machine you're using? Do you get the same answers if you rerun these benchmarks several times in a row?

If we were talking about a multi-gigabyte file, another guess might be that this was a spinning disk. But for this ~100MB file, that's well below the threshold for getting cached in RAM, so disk shouldn't be an issue. Out of curiosity, are you using a spinning disk?

Very interesting! Curious to hear more.

**Comment by Alg0ritmus** [comment]
Thank you very much!

After running `cargo run --release ` and changing "r" to "rb" the results are more reasonable.

OUTPUTS (best out of 5):

`Python`
0.01607130000000001
ee90c63b8027dbbfc98059fc91fa91b23224d33b70b1c6203d2050c0256d0a74 

`Rust`
result from update ee90c63b8027dbbfc98059fc91fa91b23224d33b70b1c6203d2050c0256d0a74                                                         050c0256d0a74
Elapsed: 21.35ms

The results are sufficient for my purposes, but mystery is still hidden. I really don't know why PY timing results are so much faster on your machine but here's my specs:

CPU: i5-8250U (4 x 1,60GHz)
RAM: 8GB DDR4 (2400MHZ)
SSD
WIN10
(hope it's sufficient)

Anyways thank you very much, I really appreciate it and sorry for interrupting you now I feel pretty lame. BTW PF 2022.

**Comment by oconnor663** [comment]
Looks like your Python time dropped by almost a factor of 10! That's interesting. Maybe it was just a matter of running it several times to warm up the caches on your machine? The remaining difference between our measurements is about a factor of 4, which isn't too wild. AVX-512 probably explains about half of that, and "who knows" explains the other half...

> Anyways thank you very much, I really appreciate it and sorry for interrupting you now I feel pretty lame.

Not at all! Benchmarking is fun but very finnicky. Next time your friends or colleagues are running benchmarks, you can give them all this mysterious advice and feel like a wizard :)

If you're interested in a deep dive, here's a bunch more: https://easyperf.net/blog/2019/08/02/Perf-measurement-environment-on-Linux

**Comment by sneves** [comment]
The other half is probably frequency, seeing that most AVX-512 capabable consumer chips max out at nearly 5 GHz, and that i5-8250U will do at best 3.4 GHz.

**Comment by Alg0ritmus** [comment]
Thanks for all advices!
