### ISSUE TITLE
md5sum is slightly faster than b3sum on tiny files

### ISSUE THREAD

**Issue by xzfc** [BLAKE3-team/BLAKE3#23]
```bash
$ for i in {1..1000};do echo $i > f$i;done
$ hyperfine 'md5sum f{1..1000}' 'b3sum f{1..1000}'
Benchmark #1: md5sum f{1..1000}
  Time (mean ± σ):      11.2 ms ±   0.6 ms    [User: 5.9 ms, System: 5.2 ms]
  Range (min … max):    10.3 ms …  13.5 ms    196 runs
 
Benchmark #2: b3sum f{1..1000}
  Time (mean ± σ):      13.7 ms ±   0.8 ms    [User: 6.2 ms, System: 7.3 ms]
  Range (min … max):    12.8 ms …  20.7 ms    168 runs
 
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
 
Summary
  'md5sum f{1..1000}' ran
    1.22 ± 0.09 times faster than 'b3sum f{1..1000}'
```

---

I guess the reason is that `read` is more effective than `mmap` on small files.

Strace output (md5sum):
```c
openat(AT_FDCWD, "f998", O_RDONLY)      = 3
fadvise64(3, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=4, ...}) = 0
read(3, "998\n", 32768)                 = 4
read(3, "", 28672)                      = 0
lseek(3, 0, SEEK_CUR)                   = 4
close(3)                                = 0
```

Strace output (b3sum):
```c
openat(AT_FDCWD, "f998", O_RDONLY|O_CLOEXEC) = 3
statx(3, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=4, ...}) = 0
mmap(NULL, 4, PROT_READ, MAP_SHARED, 3, 0) = 0x7fd03e7d2000
munmap(0x7fd03e7d2000, 4)               = 0
close(3)                                = 0
```

---

```
b3sum 0.1.1
md5sum (GNU coreutils) 8.31
```

**Comment by oconnor663** [comment]
Ooo I'm glad someone remembered to check this :-D @burntsushi mentioned running into this effect while optimizing ripgrep, so I'm not too surprised to see it here. I assume the right approach is to define some size cutoff below which we don't attempt to memory map. Maybe we can just copy whatever logic ripgrep uses? :)

**Comment by BurntSushi** [comment]
ripgrep's logic is a bit simplistic. Namely:

* If ripgrep knows it's searching a single file, or even a small number of files, then it uses memory maps. Even if the files are small, the performance difference here is so small that it's likely negligible. (I see that the performance difference reported in this issue is `0.3 ms`, which also seems not worth worrying about.)
* In all other cases, ripgrep uses standard `read` calls.

ripgrep could probably use memory maps a bit more if it did an extra stat call to determine the size of the file. But then you would need to pay for that extra stat call, which isn't always necessary and can actually wind up being quite a hit. Regardless, that type of optimization may make sense for b3sum. I'm not sure!
