### ISSUE TITLE
Can I Use Keyed Hashing Mode With Using Same Key?

### ISSUE THREAD

**Issue by whatamnotsaying** [BLAKE3-team/BLAKE3#239]
.
.
.
hashN-2 = blake3(counterN-2, key)
hashN-1 = blake3(counterN-1, key)
hashN = blake3(counterN, key)

lets say attacker knows this hash results and also counters. Can attacker say anything about what will be hashN+1 result without bruteforcing 256 bit key? (yes i am trying to make cipher. because i am curious. but i didn't ask cipher. it is only about blake3 keyed hashing mode for properly using it)

**Comment by oconnor663** [comment]
> Can attacker say anything about what will be hashN+1 result without bruteforcing 256 bit key?

No, they can't. If they could, that would represent a serious flaw in BLAKE3, as it would with any other keyed cryptographic hash function. Specifically, keyed BLAKE3 is intended to behave like a "pseudorandom function".

For what it's worth, it might be slightly more natural to use BLAKE3's extended output to generate a pseudorandom stream, rather than incrementing a counter on the input side. That's what I'm doing e.g. here: https://github.com/oconnor663/bessie.
