### ISSUE TITLE
[Question] About benchmark results in README page

### ISSUE THREAD

**Issue by phantomcraft** [BLAKE3-team/BLAKE3#265]
The benchmark says that are 16KiB inputs.

Does it mean hash a 16KiB input repeatedly (over and over) or hashing and incrementing the block counter for each hash operation?

**Comment by sneves** [comment]
The relevant code is (I think?) [here](https://github.com/BLAKE3-team/BLAKE3/blob/master/benches/bench.rs#L221-L284), from which I guess it's hashing the same 16 KB over and over?

**Comment by oconnor663** [comment]
The exact benchmarks I used to generate that graph [are in this file](https://github.com/BLAKE3-team/BLAKE3-specs/blob/master/benchmarks/benches/bench.rs), which uses the (fancier) Criterion library instead of the (minimalistic) standard benchmarking harness. But they're doing the same thing as the one Samuel linked above, hashing separate 16 KiB inputs over and over and averaging out how long it takes to do that. If you scroll down, you'll see [a comment about how it's not quite the same input every time](https://github.com/BLAKE3-team/BLAKE3-specs/blob/ea51a3ac997288bf690ee82ac9cfc8b3e0e60f2a/benchmarks/benches/bench.rs#L76-L78), but it's pretty close to that. If you run somethig like this, you should be able to reproduce something like the README graph (plus several other hash functions that I omitted from the graph):

```
git clone git@github.com:BLAKE3-team/BLAKE3-specs
cd BLAKE3-specs/benchmarks
cargo +nightly bench '16384$'
```

All that said, you might also be asking "Is calling `.update()` in a loop just as fast as hashing individiual inputs of the same length?" and the answer to that question is basically yes. If you benchmark both approaches, you shouldn't see much of a difference. The implementation in this repo actually takes on some extra complexity to avoid making `.update()` slower than `hash()`; see for example [this comment](https://github.com/BLAKE3-team/BLAKE3/blob/f84636e59ce575e5dd127399e0c7de0c1ea595da/src/lib.rs#L741-L747).

**Comment by phantomcraft** [comment]
@oconnor663

Thank you very much.

**Comment by phantomcraft** [comment]
@oconnor663 

I have a doubt about results of benchmarks.

Are numbers in the README  the amount of data that is read per second or concatenation of Blake3 outputs per 16 KiB block read?

**Comment by oconnor663** [comment]
> Are numbers in the README the amount of data that is read per second

Yes.

> or concatenation of Blake3 outputs per 16 KiB block read?

No, the bechmarks only compute a regular 32-byte output for each input. In general we haven't benchmarked the extended outputs. In theory they should be almost exactly the same as our input speed, because the input and output sizes for our compression function are equal. But in practice, I haven't yet gotten all the same optimizations working on the extended output side, and it's actually much slower.
