### ISSUE TITLE
Why not provide as_str?

### ISSUE THREAD

**Issue by auts2022** [BLAKE3-team/BLAKE3#266]
There's a method to_string() in this crate to convert the hash into String, I suggest you also provide as_str() to convert the hash into &str.

**Comment by oconnor663** [comment]
This is a great question, which goes right to the heart of how references and lifetimes work in Rust. It turns out that `Hash` _can't_ implement something like `.as_str()`, because it doesn't store hex characters internally. The `.to_string()` method creates an `ArrayString` and returns that by value, so in effect the hex characters wind up in the caller's stack memory. But a `.as_str()` method would need to return a reference that points somewhere, and the question becomes, where should it point? The only\* way to make it work would be to have an `ArrayString` or similar contained inside the `Hash` itself, and to point back to that. But that would triple the size of `Hash` for all callers, which isn't a good trade.

\* _Technically_ we could create a `Box<ArrayString>` and then call `Box::leak` to make this work, but leaking memory every time you call `.as_str()` isn't what anybody wants :)
