### ISSUE TITLE
Is it possible to get an updated & optimized JAVA implementation ?

### ISSUE THREAD

**Issue by robertveda** [BLAKE3-team/BLAKE3#276]
Hi,

I'm using bountycastle lib which purpose an implementation of Blake3, but after doing some benchmarking
it's not optimized (2 x slower than SHA3 -256)  (https://www.bouncycastle.org/releasenotes.html)

Any suggestions of other java library ? thanks a lot.
King regards,
Robert.

**Comment by oconnor663** [comment]
The magic term to google here is "JNI", which is when Java code calls into C code or similar. When I google "blake3 jni", this project shows up: https://github.com/alephium/blake3-jni. It doesn't look like it's been maintained since 2020, so I'd be careful about depending on it in any important codebase, but if you want to experiment with it there's a chance it still works... (Our underlying C API hasn't had any backwards-incompatible changes, so you might want to start by updating the vendored copy.)
