### ISSUE TITLE
Minimum crypto secure hash bit length

### ISSUE THREAD

**Issue by PavelWolfDark** [BLAKE3-team/BLAKE3#278]
Ave, cryptovikings!
Thanks for your work.
I'm developing Darkwolf UID (DWUID) — universally unique lexicographic human-friendly decentralized identifier.
I want to use BLAKE3 for Hash version (v4) of DWUID and I need to know what is the minimum cryptographically secure output hash length in bits that can be represented?

**Comment by oconnor663** [comment]
Cryptographic security isn't a single concept, so you'd need to be more specific about exactly what you need. In particular, many applications need "128 bits of collision resistance", which is what you get from the default 256-bit (32-byte) digest. But some applications only need "preimage resistance", in which case you can get away with a shorter digest. If these are new concepts for you, I'd suggest sticking with the default-length digest.

**Comment by PavelWolfDark** [comment]
@oconnor663 
Can I use a 128-bit digest, if so how likely are collisions then? How about a 116-bit digest, or should the digest bits be a multiple of 8, if so, which bits can I cut out?

**Comment by oconnor663** [comment]
> if so how likely are collisions then?

The rule of thumb is that you get a ~50% chance of a collision after a number of operations equal to the square root of the size of the search space. The square root of 2<sup>128</sup> is 2<sup>64</sup>, so collisions become likely as you approach 2<sup>64</sup> operations. That amound of work is generally considered "very expensive but doable in practice".

> Can I use a 128-bit digest

I don't know. Again, this isn't a simple question. It depends on what you're doing and what your threat model is. (I.e. are there attackers out there trying to produce collisions? Or is it just a question of random bugs?) My recommendation is that you stick with the default length of 256 bits, because that's safe for just about everyone. If you'd like to study more about this and make more aggressive choices in the future, [here's a book I recommend](https://nostarch.com/seriouscrypto). (The author is also a BLAKE3 coauthor.)

> which bits can I cut out?

If you experiment with [`OutputReader`](https://docs.rs/blake3/latest/blake3/struct.OutputReader.html) or `b3sum --length=...`, you'll see that shorter outputs just chop bytes off of the end. So in general, _if_ you know it's safe for you to use a shorter output, _then_ that's the standard way to do it.
