### ISSUE TITLE
Build Failing, Bitdefender Detects Gen:Variant.Razy.609843

### ISSUE THREAD

**Issue by tERyceNzAchE** [BLAKE3-team/BLAKE3#59]
Bitdefender is removing b3sum and preventing a successful build using `cargo install b3sum`.

Error:
The file \cargo-installJYtDLo\release\build\anyhow-abe5dfc7615735a9\build_script_build-abe5dfc7615735a9.exe is infected with Gen:Variant.Razy.609843 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Comment by oconnor663** [comment]
It's not clear to me what we can do about this. Any suggestions?

**Comment by cesarb** [comment]
Given the full path, the quarantined file was the compiled `build.rs` from the `anyhow` crate (https://github.com/dtolnay/anyhow/blob/master/build.rs), which is one of `b3sum`'s dependencies (that is, `b3sum` didn't even compile, since the dependencies have to compile first).

Since the crate affected is not `b3sum` or `blake3`, this issue should be closed. And it doesn't even make sense to open it as an issue on the `anyhow` crate, since there's nothing they can do. It's a false positive, and should be reported to _Bitdefender_, which is the one actually responsible for the build failing. According to Wikipedia (https://en.wikipedia.org/wiki/Bitdefender#Trojan.FakeAlert.5), it is not the first time something like this happens.
